name: 'Setup buildcache'
description: 'Install buildcache and add it to PATH for Windows and Linux'
author: 'Your Name'

inputs:
  version:
    description: 'buildcache version to install (e.g., v0.28.1). If not specified, uses latest release.'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Determine buildcache version
      id: version
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "latest" ]; then
          echo "Getting latest buildcache release..."
          LATEST_VERSION=$(curl -s https://gitlab.com/api/v4/projects/bits-n-bites%2Fbuildcache/releases | jq -r '.[0].tag_name')
          if [ "$LATEST_VERSION" = "null" ] || [ -z "$LATEST_VERSION" ]; then
            echo "Error: Could not fetch latest version from GitLab API"
            exit 1
          fi
          echo "version=$LATEST_VERSION" >> $GITHUB_OUTPUT
          echo "Latest version: $LATEST_VERSION"
        else
          VERSION="${{ inputs.version }}"
          if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version must be in format vX.Y.Z (e.g., v0.31.5)"
            exit 1
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Using specified version: $VERSION"
        fi

    - name: Install buildcache (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        echo "Installing buildcache $VERSION for Linux..."
        
        # Install required dependencies
        echo "Installing required dependencies..."
        sudo apt-get update -qq
        # Install OpenSSL 1.1 libraries (buildcache requires libcrypto.so.1.1)
        if ! sudo apt-get install -y libssl1.1; then
          echo "libssl1.1 not available in default repos, adding focal repo for compatibility..."
          echo "deb http://security.ubuntu.com/ubuntu focal-security main" | sudo tee /etc/apt/sources.list.d/focal-security.list
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
          sudo apt-get update -qq
          sudo apt-get install -y libssl1.1
        fi
        
        # Determine download URL based on version
        # v0.31.4+ uses buildcache-linux-amd64.tar.gz
        # v0.31.3 and earlier use buildcache-linux.tar.gz
        VERSION_NUM=${VERSION#v}
        MAJOR=$(echo $VERSION_NUM | cut -d. -f1)
        MINOR=$(echo $VERSION_NUM | cut -d. -f2)
        PATCH=$(echo $VERSION_NUM | cut -d. -f3)
        
        if [[ $MAJOR -eq 0 && $MINOR -lt 30 ]]; then
          # v0.29.x and earlier use GitLab package registry
          DOWNLOAD_URL="https://gitlab.com/api/v4/projects/49153623/packages/generic/releases/$VERSION/buildcache-linux.tar.gz"
          echo "Using package registry URL for $VERSION (≤v0.29.x)"
        elif [[ $MAJOR -gt 0 ]] || [[ $MAJOR -eq 0 && $MINOR -gt 31 ]] || [[ $MAJOR -eq 0 && $MINOR -eq 31 && $PATCH -ge 4 ]]; then
          # v0.31.4+ uses buildcache-linux-amd64.tar.gz
          DOWNLOAD_URL="https://gitlab.com/bits-n-bites/buildcache/-/releases/$VERSION/downloads/buildcache-linux-amd64.tar.gz"
          echo "Using new URL format for $VERSION (v0.31.4+)"
        else
          # v0.30.0 to v0.31.3 use buildcache-linux.tar.gz
          DOWNLOAD_URL="https://gitlab.com/bits-n-bites/buildcache/-/releases/$VERSION/downloads/buildcache-linux.tar.gz"
          echo "Using legacy URL format for $VERSION (v0.30.0-v0.31.3)"
        fi
        
        # Download with error handling
        if ! curl -L "$DOWNLOAD_URL" -o buildcache.tar.gz --fail; then
          echo "Error: Failed to download buildcache $VERSION. Please check if this version exists."
          echo "Available releases: https://gitlab.com/bits-n-bites/buildcache/-/releases"
          exit 1
        fi
        
        # Create installation directory
        INSTALL_DIR="$HOME/.local/buildcache-$VERSION"
        mkdir -p "$INSTALL_DIR"
        
        # Extract with error handling
        if ! tar -xzf buildcache.tar.gz -C "$INSTALL_DIR"; then
          echo "Error: Failed to extract buildcache archive"
          rm -f buildcache.tar.gz
          rm -rf "$INSTALL_DIR"
          exit 1
        fi
        
        # Debug: Show extracted contents
        echo "Extracted archive contents:"
        find "$INSTALL_DIR" -type f | head -20
        
        # Find the buildcache binary recursively
        BINARY_FILE=$(find "$INSTALL_DIR" -name "buildcache" -type f -executable | head -1)
        if [ -z "$BINARY_FILE" ]; then
          echo "Error: buildcache binary not found in extracted archive"
          echo "All files in extracted directory:"
          find "$INSTALL_DIR" -type f
          rm -f buildcache.tar.gz
          rm -rf "$INSTALL_DIR"
          exit 1
        fi
        
        # Get the directory containing the binary
        BINARY_PATH=$(dirname "$BINARY_FILE")
        echo "Found buildcache binary at: $BINARY_FILE"
        
        # Make binary executable
        chmod +x "$BINARY_PATH/buildcache"
        
        # Add to PATH for current session and future steps
        echo "$BINARY_PATH" >> $GITHUB_PATH
        export PATH="$BINARY_PATH:$PATH"
        
        # Verify installation
        if ! buildcache --version; then
          echo "Error: buildcache installation verification failed"
          exit 1
        fi
        
        # Show where buildcache was installed
        INSTALLED_PATH=$(which buildcache)
        echo "buildcache $VERSION installed successfully on Linux"
        echo "Binary location: $INSTALLED_PATH"
        echo "Installation directory: $BINARY_PATH"
        
        # Cleanup downloaded archive
        rm -f buildcache.tar.gz

    - name: Install buildcache (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $VERSION = "${{ steps.version.outputs.version }}"
        Write-Host "Installing buildcache $VERSION for Windows..."
        
        # Determine download URL based on version
        $VERSION_NUM = $VERSION -replace '^v', ''
        $VERSION_PARTS = $VERSION_NUM -split '\.'
        $MAJOR = [int]$VERSION_PARTS[0]
        $MINOR = [int]$VERSION_PARTS[1]
        $PATCH = [int]$VERSION_PARTS[2]
        
        if ($MAJOR -eq 0 -and $MINOR -lt 30) {
          # v0.29.x and earlier use GitLab package registry
          $DOWNLOAD_URL = "https://gitlab.com/api/v4/projects/49153623/packages/generic/releases/$VERSION/buildcache-windows.zip"
          Write-Host "Using package registry URL for $VERSION (≤v0.29.x)"
        } else {
          # v0.30.0+ use releases downloads
          $DOWNLOAD_URL = "https://gitlab.com/bits-n-bites/buildcache/-/releases/$VERSION/downloads/buildcache-windows.zip"
          Write-Host "Using releases URL for $VERSION (v0.30.0+)"
        }
        
        # Download with error handling
        try {
          Invoke-WebRequest -Uri $DOWNLOAD_URL -OutFile buildcache.zip -ErrorAction Stop
        } catch {
          Write-Host "Error: Failed to download buildcache $VERSION. Please check if this version exists." -ForegroundColor Red
          Write-Host "Available releases: https://gitlab.com/bits-n-bites/buildcache/-/releases" -ForegroundColor Yellow
          exit 1
        }
        
        # Create installation directory
        $InstallDir = "$env:USERPROFILE\.local\buildcache-$VERSION"
        New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
        
        # Extract with error handling
        try {
          Expand-Archive -Path buildcache.zip -DestinationPath $InstallDir -ErrorAction Stop
        } catch {
          Write-Host "Error: Failed to extract buildcache archive" -ForegroundColor Red
          Remove-Item -Force buildcache.zip -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force $InstallDir -ErrorAction SilentlyContinue
          exit 1
        }
        
        # Debug: Show extracted contents
        Write-Host "Extracted archive contents:"
        Get-ChildItem -Recurse $InstallDir | Select-Object -First 20 | ForEach-Object { Write-Host $_.FullName }
        
        # Find the buildcache binary recursively
        $BinaryFile = Get-ChildItem -Recurse $InstallDir -Name "buildcache.exe" | Select-Object -First 1
        if (-not $BinaryFile) {
          Write-Host "Error: buildcache.exe not found in extracted archive" -ForegroundColor Red
          Write-Host "All files in extracted directory:" -ForegroundColor Yellow
          Get-ChildItem -Recurse $InstallDir | ForEach-Object { Write-Host $_.FullName }
          Remove-Item -Force buildcache.zip -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force $InstallDir -ErrorAction SilentlyContinue
          exit 1
        }
        
        # Get the directory containing the binary
        $BinaryPath = Split-Path -Parent (Join-Path $InstallDir $BinaryFile)
        Write-Host "Found buildcache binary at: $(Join-Path $InstallDir $BinaryFile)"
        
        # Add to PATH for current session and future steps
        echo $BinaryPath | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        $env:PATH = "$BinaryPath;$env:PATH"
        
        # Verify installation
        try {
          $versionOutput = buildcache --version 2>&1
          if ($LASTEXITCODE -ne 0) {
            throw "buildcache returned exit code $LASTEXITCODE"
          }
          
          # Show where buildcache was installed
          $InstalledPath = (Get-Command buildcache).Source
          Write-Host "buildcache $VERSION installed successfully on Windows"
          Write-Host "Binary location: $InstalledPath"
          Write-Host "Installation directory: $BinaryPath"
        } catch {
          Write-Host "Error: buildcache installation verification failed" -ForegroundColor Red
          exit 1
        }
        
        # Cleanup downloaded archive
        Remove-Item -Force buildcache.zip -ErrorAction SilentlyContinue

branding:
  icon: 'box'
  color: 'blue'
